version: "3.7"
networks:
  discord_bot_network:
    name: discord_bot_network
services:
  bot:
    container_name: bot_container
    image: registry.gitlab.com/zainal21/discord-bot:${BOT_IMAGE_VERSION}
    volumes:
      - data_volume:/src/usr/app
    networks:
      - discord_bot_network
volumes:
  data_volume:
